version: "3.9"

services:
  api:
    build: ../../apps/api
    container_name: tfg-api
    ports:
      - "3000:3000"
    env_file:
      - ../../.env.example
    volumes:
      - ../../apps/api:/app
    command: npm run dev

  web:
    build: ../../apps/web
    container_name: tfg-web
    ports:
      - "5173:5173"
    volumes:
      - ../../apps/web:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 5173
